id: app
title: Windows Defender Antivirus software
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/windows-defender-antivirus
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of Windows Defender Antivirus software
    long: Generates compliance documentation of Windows Defender Antivirus software
      as it pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST SP 800-171 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Windows Defencer Antivurs softare provides protection against malicious code.

    This application will make sure you are properly using Windows Defender Antivirus
    software to protect CUI (Controlled Unclassified Information) as per NIST SP 800-171
    controls.
questions: []
output:
- id: ssp_nist800171r1_3_4_8
  title: NIST SP 800-171 3.4.8 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to apply deny-by-exception
    (blacklist) policy to prevent the use of unauthorized software or denyall, permit-by-exception
    (whitelisting) policy to allow the execution of authorized software. Windows Defencer
    Antivurs softare provides protection against malicious code.

- id: ssp_nist800171r1_3_4_9
  title: NIST SP 800-171 3.4.9 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses Windows Defender Antivirus software to control and monitor user-installed software. Windows Defencer Antivurs softare provides protection against malicious code.

- id: ssp_nist800171r1_3_13_1
  title: NIST SP 800-171 3.13.1 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to monitor, control,
    and protect communications (i.e., information transmitted or received by organizational
    systems) at the external boundaries and key internal boundaries of organizational
    systems. Windows Defencer Antivurs softare provides protection against malicious
    code.

- id: ssp_nist800171r1_3_13_12
  title: NIST SP 800-171 3.13.12 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to prohibit remote activation
    [Footnote: Dedicated video conferencing systems, which rely on one of the participants
    calling or connecting to the other party to activate the video conference, are
    excluded.] of collaborative computing devices and provide indication of devices
    in use to users present at the device. Windows Defencer Antivurs softare provides
    protection against malicious code.

- id: ssp_nist800171r1_3_14_2
  title: NIST SP 800-171 3.14.2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to provide protection
    from malicious code at appropriate locations within organizational systems. Windows
    Defencer Antivurs softare provides protection against malicious code.

- id: ssp_nist800171r1_3_14_3
  title: NIST SP 800-171 3.14.3 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to monitor system security
    alerts and advisories and take appropriate actions in response. Windows Defencer
    Antivurs softare provides protection against malicious code.

- id: ssp_nist800171r1_3_14_4
  title: NIST SP 800-171 3.14.4 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to update malicious
    code protection mechanisms when new releases are available. Windows Defencer Antivurs
    softare provides protection against malicious code.

- id: ssp_nist800171r1_3_14_5
  title: NIST SP 800-171 3.14.5 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to perform periodic
    scans of organizational systems and real-time scans of files from external sources
    as files are downloaded, opened, or executed. Windows Defencer Antivurs softare
    provides protection against malicious code.

- id: ssp_nist800171r1_3_14_6
  title: NIST SP 800-171 3.14.6 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Windows Defender Antivirus software to monitor organizational
    systems including inbound and outbound communications traffic, to detect attacks
    and indicators of potential attacks. Windows Defencer Antivurs softare provides
    protection against malicious code.

