id: app
title: Plan of Action and Milestones (PO&AM) for NIST SP 800-53
instance-name: |
  {% if description.identifier %}
    {{description.identifier}}
  {% else %}
    New POAM
  {% endif %}
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4/poam
- govready.com/apps/compliance/2018/general/activity
- govready.com/apps/compliance/2018/POAM
version: 0.5
icon: app.png
catalog:
  category: Tasks
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/govready-apps-dev/tree/master/out/apps/POAM-800-53r4
  description:
    short: PO&AM tracking for NIST RMF (NIST SP 800-53) Compliance
    long: PO&AM tracking for NIST RMF (NIST SP 800-53) Compliance
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: This application will prepare a Plan of Action and Milestones (POAM) for
    managing the security of NIST RMF as per NIST SP 800-53r4 controls.
questions:
- id: description
  title: Description of the POAM
  type: module
  module-id: description
- id: progress
  title: Report Progress
  type: module
  module-id: progress
output:
- complete_text.md
