id: app
title: Microsoft Windows Workstation
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/windows-workstation
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of Microsoft Windows Workstation
    long: Generates compliance documentation of Microsoft Windows Workstation as it
      pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST SP 800-171 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Microsoft Microsoft Windows workstations are personal computers.

    This application will make sure you are properly using Microsoft Windows Workstation
    to protect CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions:
- id: questions
  title: Questions about the Windows Workstations
  type: module
  module-id: questions
output:
- ssp_nist800171r1_3_1_1.md
- ssp_nist800171r1_3_1_2.md
- ssp_nist800171r1_3_1_8.md
- ssp_nist800171r1_3_1_10.md
- ssp_nist800171r1_3_1_17.md
- ssp_nist800171r1_3_1_19.md
- ssp_nist800171r1_3_3_1.md
- ssp_nist800171r1_3_3_2.md
- ssp_nist800171r1_3_3_7.md
- ssp_nist800171r1_3_3_8.md
- ssp_nist800171r1_3_4_2.md
- ssp_nist800171r1_3_5_1.md
- ssp_nist800171r1_3_5_2.md
- ssp_nist800171r1_3_5_7.md
- ssp_nist800171r1_3_5_11.md
- ssp_nist800171r1_3_13_16.md
