id: app
title: CentOS 7.3
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/centos
- govready.com/apps/compliance/2017/centos-7
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of CentOS 7.3
    long: Generates compliance documentation of CentOS 7.3 as it pertains to managing
      the security of CUI (Controlled Unclassified Information) as per NIST SP 800-171
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    CentOS 7.3 is a Linux operating system functionality compatible with Red Hat Enterprise
    Linux.

    This application will make sure you are properly using CentOS 7.3 to protect CUI
    (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions: []
output: []
