id: app
title: Digital Ocean Data Center
type: project
version: 1
protocol: govready.com/apps/compliance/2017/data-center
icon: app.png
catalog:
  category: People, Places, and Things
  vendor: GovReady PBC
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.95
  source_url: https://github.com/GovReady/q-ssp-modules/modules/digital_ocean_data_center
  description:
    short: |
      Provides information about Digital Ocean's cloud data center.
    long: |
      Provides information about Digital Ocean's cloud data center.
  recommended_for:
  - key_short: Org
    value: Large
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
questions:
- id: name_and_location
  title: Name and Location
  type: text
  impute:
  - value: DigitalOcean's Cloud Data Center
output:
- ssp_nistsp800171r1_3_1_1.md
- ssp_nistsp800171r1_poams.md
