id: app
title: Project Manager (PM)
type: project
version: 1
protocol: fed_poc_pm
icon: app.png

catalog:
  category: People and Roles
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.1
  source_url: https://github.com/GovReady/govready-q-drupal-fed-people
  description:
    short: |
      Project Manager
    long: |
      # Project Manager

      This module provides point of contact information for the Project Manager (PM) supporting a Drupal website for a US Federal government agency.

      ## Who Should Use:

      - Managers of Drupal sites at Federal agencies

      ## How This Aids Compliance

      Completion of these tasks addresses the following controls in FISMA NIST SP 800-53:

      - ??? (role PM)

      ## What App Does:

      - Gathers point of contact information for an PM

      ## What You Do:

      - Complete contact information

      ## Compliance App Support
      This task collection is maintained by GovReady PBC.

      Invite support@govready.com to any conversation for support. Charges may apply.
      Alternatively, invite support@govready.com to a [Task.kiwi](https://task.kiwi).

  recommended_for:
    - key_short: Org
      value: federal
    - key_short: Tech
      value: Drupal
    - key_short: Role
      value: Project Manager

questions:
  - id: poc
    title: PM
    module-id: poc
    type: module

output:
  - title: Document
    format: markdown
    id: ssp_template
    template: |

      {% if not poc.q1_name %}
        The system will have a PM.
      {% else %}

        The Project Manager for the system is {{poc.q1_name}} ({{poc.q5_email}}).

      {% endif %}
tests:
  simple:
    answers:
      poc:
        answers:
          q1_name: Jane Johnson
          q3_ev: employee
          q5_email: jane@example.com
          q6_work_phone: "202-555-0000"
          q7_mobile_phone: "202-555-0001"
