id: app
title: Points of Contact Directory
type: project
version: 1
snippet:
  format: html
  template: ''
catalog:
  description:
    short: |
      Maintain a Directory of the various Points of Contact
    long: |
      ## Point of Contact Directory

      **By GovReady**

      This tool will help you generate and maintain a directory of various Points of Contacts.

      This demo version just captures the name of a Point of Contact, but the questions
      can be customized with each install.
interstitial:
  format: markdown
  template: |
    ## Points of Contact Directory

    Create a comprehensive list of contacts for your system

    - Who does what for your system
    - How to reach them

    Are you ready?
introduction:
  format: markdown
  template: |
    Add a new Point of Contact for your system.
invitation_to_task_interstitial:
  format: markdown
  template: |
    ## Thanks for accepting {{invitation.from_user}}'s invitation

    You've been asked to help with {{task.title}} for {{project}}.

    We'll tell {{invitation.from_user}} you're getting started.
export_button_label: Export System Description and Control Information
questions:
- id: poc_person
  title: Add a person as Point of Contact
  type: module-set
  module-id: poc_person
  tab: Points of Contact
  group: Contacts
- id: poc_org
  title: Add an organization as Point of Contact
  type: module-set
  module-id: poc_org
  tab: Points of Contact
  group: Contacts
output:
- tab: Points of Contact
  format: markdown
  template: |
    <div style="text-align:center;">

    ## Create a Point of Contact

    ![](icon_system_capital.png)

    </div>
