id: app
title: Server Room
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/server-room
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of a Server Room
    long: Generates compliance documentation for a server room as it pertains to managing
      the security of CUI (Controlled Unclassified Information) as per NIST SP 800-171
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    A server room is an on-premises data center for segrating computer servers and
    network equipment from the rest of the facility.

    This application will make sure you are properly using a server room to protect
    CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions:
- id: questions
  title: Questions about the Server Room
  type: module
  module-id: questions
output:
- ssp_nist800171r1_3_1_1.md
- ssp_nist800171r1_3_8_1.md
- ssp_nist800171r1_3_8_2.md
- ssp_nist800171r1_3_10_1.md
- ssp_nist800171r1_3_10_2.md
