id: app
title: Employee Handbook
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/employee-handbook
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of Employee Handbook
    long: Generates compliance documentation of Employee Handbook as it pertains to
      managing the security of CUI (Controlled Unclassified Information) as per NIST
      SP 800-171 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Employee Handbook is a set of official organization policies.

    This application will make sure you are properly using Employee Handbook to protect
    CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions: []
output:
- ssp_nist800171r1_3_2_1.md
- ssp_nist800171r1_3_2_2.md
- ssp_nist800171r1_3_2_3.md
- ssp_nist800171r1_3_6_1.md
- ssp_nist800171r1_3_9_2.md
