id: app
title: Cloud.gov
type: project
protocol: opencontrol
opencontrol_fetch_date: '2017-05-17T02:55:44.333719+00:00'
version: 0.2
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.2
  source_url: https://github.com/GovReady/some-repo-here
  description:
    short: |
      Host on Cloud.gov using OpenControl.
    long: |
      This app will help you configure and operate your systems on Cloud.gov, using Cloud.gov's OpenControl data.
  recommended_for:
  - key_short: Org
    value: Large
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
questions: []
output:
- ssp_template_mp_2.md
- ssp_template_ia_4__4.md
- ssp_template_sa_11__8.md
- ssp_template_ma_5__1.md
- ssp_template_ac_2__12.md
- ssp_template_cp_2.md
- ssp_template_at_4.md
- ssp_template_ia_8__2.md
- ssp_template_ma_1.md
- ssp_template_si_12.md
- ssp_template_ac_4__21.md
- ssp_template_ia_2__5.md
- ssp_template_ac_17__2.md
- ssp_template_sa_9__2.md
- ssp_template_sa_4__8.md
- ssp_template_cp_7__3.md
- ssp_template_ps_4.md
- ssp_template_ac_2__1.md
- ssp_template_sc_7.md
- ssp_template_ac_6__1.md
- ssp_template_ac_11.md
- ssp_template_sa_5.md
- ssp_template_pe_11.md
- ssp_template_ia_2.md
- ssp_template_si_1.md
- ssp_template_cp_9__3.md
- ssp_template_ac_2__5.md
- ssp_template_ac_2__2.md
- ssp_template_ac_2__4.md
- ssp_template_sc_12__2.md
- ssp_template_au_5.md
- ssp_template_ma_3__2.md
- ssp_template_pe_10.md
- ssp_template_cp_4.md
- ssp_template_ac_17__4.md
- ssp_template_ps_6.md
- ssp_template_ps_3__3.md
- ssp_template_sc_8.md
- ssp_template_sc_23.md
- ssp_template_ca_2__1.md
- ssp_template_ia_5__3.md
- ssp_template_cp_10__2.md
- ssp_template_ia_5__6.md
- ssp_template_ia_5__4.md
- ssp_template_sa_9__1.md
- ssp_template_si_7__1.md
- ssp_template_ca_6.md
- ssp_template_si_8.md
- ssp_template_ir_3__2.md
- ssp_template_mp_5.md
- ssp_template_cp_9__1.md
- ssp_template_ma_2.md
- ssp_template_pe_6__1.md
- ssp_template_au_6__1.md
- ssp_template_sa_8.md
- ssp_template_ac_2__7.md
- ssp_template_cm_2__2.md
- ssp_template_ps_7.md
- ssp_template_ia_2__11.md
- ssp_template_sa_11__1.md
- ssp_template_ca_2.md
- ssp_template_mp_3.md
- ssp_template_ir_5.md
- ssp_template_sa_11.md
- ssp_template_ca_8.md
- ssp_template_au_2__3.md
- ssp_template_ia_8__1.md
- ssp_template_cp_1.md
- ssp_template_ma_6.md
- ssp_template_sa_9__5.md
- ssp_template_at_1.md
- ssp_template_ca_3__5.md
- ssp_template_sc_13.md
- ssp_template_sc_21.md
- ssp_template_sc_7__7.md
- ssp_template_ia_8.md
- ssp_template_sc_15.md
- ssp_template_cp_2__1.md
- ssp_template_ca_3.md
- ssp_template_si_4__14.md
- ssp_template_cp_7__2.md
- ssp_template_ia_5__7.md
- ssp_template_ir_7__2.md
- ssp_template_ps_1.md
- ssp_template_sa_9__4.md
- ssp_template_pe_2.md
- ssp_template_si_4__16.md
- ssp_template_au_7__1.md
- ssp_template_ma_3.md
- ssp_template_sc_7__5.md
- ssp_template_ac_2__9.md
- ssp_template_sc_12__3.md
- ssp_template_ca_9.md
- ssp_template_sa_4__1.md
- ssp_template_cp_7.md
- ssp_template_ir_7.md
- ssp_template_ac_12.md
- ssp_template_cp_3.md
- ssp_template_au_9.md
- ssp_template_ir_9__3.md
- ssp_template_sc_28.md
- ssp_template_ia_2__8.md
- ssp_template_ma_3__3.md
- ssp_template_pe_3.md
- ssp_template_si_3.md
- ssp_template_ac_2__10.md
- ssp_template_sa_10__1.md
- ssp_template_si_8__2.md
- ssp_template_sa_1.md
- ssp_template_ac_2.md
- ssp_template_cm_3.md
- ssp_template_sc_8__1.md
- ssp_template_cp_4__1.md
- ssp_template_ac_6__9.md
- ssp_template_si_4__4.md
- ssp_template_ia_2__1.md
- ssp_template_ir_6.md
- ssp_template_pl_1.md
- ssp_template_pe_1.md
- ssp_template_mp_7__1.md
- ssp_template_sc_7__12.md
- ssp_template_sc_17.md
- ssp_template_cp_8.md
- ssp_template_si_4.md
- ssp_template_sa_9.md
- ssp_template_au_2.md
- ssp_template_ia_5__11.md
- ssp_template_ac_7.md
- ssp_template_pe_12.md
- ssp_template_au_11.md
- ssp_template_ia_2__12.md
- ssp_template_si_3__1.md
- ssp_template_cm_8.md
- ssp_template_ma_4.md
- ssp_template_pe_8.md
- ssp_template_pe_14.md
- ssp_template_cp_6__3.md
- ssp_template_sa_4__9.md
- ssp_template_ca_7__1.md
- ssp_template_ac_5.md
- ssp_template_pe_13.md
- ssp_template_au_8.md
- ssp_template_pe_15.md
- ssp_template_si_16.md
- ssp_template_sc_22.md
- ssp_template_ca_3__3.md
- ssp_template_ir_1.md
- ssp_template_sc_7__13.md
- ssp_template_ca_5.md
- ssp_template_pe_5.md
- ssp_template_ac_10.md
- ssp_template_ca_2__2.md
- ssp_template_sc_7__8.md
- ssp_template_sc_18.md
- ssp_template_si_7.md
- ssp_template_ac_17__3.md
- ssp_template_au_9__2.md
- ssp_template_ir_9__4.md
- ssp_template_cp_6.md
- ssp_template_ir_8.md
- ssp_template_ac_17__1.md
- ssp_template_au_9__4.md
- ssp_template_ir_6__1.md
- ssp_template_cm_6.md
- ssp_template_ir_9.md
- ssp_template_ac_6__10.md
- ssp_template_ac_17__9.md
- ssp_template_au_8__1.md
- ssp_template_at_2.md
- ssp_template_ac_6__5.md
- ssp_template_cm_1.md
- ssp_template_sa_11__2.md
- ssp_template_mp_7.md
- ssp_template_cp_10.md
- ssp_template_ir_4.md
- ssp_template_pe_14__2.md
- ssp_template_at_2__2.md
- ssp_template_sa_4__2.md
- ssp_template_si_10.md
- ssp_template_cp_2__3.md
- ssp_template_ia_1.md
- ssp_template_ia_5__2.md
- ssp_template_ia_2__2.md
- ssp_template_si_7__7.md
- ssp_template_pe_6.md
- ssp_template_sc_2.md
- ssp_template_sc_1.md
- ssp_template_si_11.md
- ssp_template_ac_6.md
- ssp_template_ca_2__3.md
- ssp_template_au_7.md
- ssp_template_pe_13__3.md
- ssp_template_ps_8.md
- ssp_template_ca_7.md
- ssp_template_ma_5.md
- ssp_template_si_4__2.md
- ssp_template_si_2__3.md
- ssp_template_ac_17.md
- ssp_template_si_3__7.md
- ssp_template_au_6.md
- ssp_template_sc_39.md
- ssp_template_pe_17.md
- ssp_template_sc_19.md
- ssp_template_mp_6.md
- ssp_template_ia_3.md
- ssp_template_pl_8.md
- ssp_template_cm_2__3.md
- ssp_template_si_4__1.md
- ssp_template_cp_7__1.md
- ssp_template_ac_14.md
- ssp_template_ac_11__1.md
- ssp_template_sc_7__4.md
- ssp_template_au_4.md
- ssp_template_cm_2__1.md
- ssp_template_sc_12.md
- ssp_template_si_4__23.md
- ssp_template_ac_3.md
- ssp_template_sc_20.md
- ssp_template_ca_8__1.md
- ssp_template_mp_5__4.md
- ssp_template_au_6__3.md
- ssp_template_ca_1.md
- ssp_template_sc_6.md
- ssp_template_ir_2.md
- ssp_template_pe_9.md
- ssp_template_si_4__5.md
- ssp_template_si_6.md
- ssp_template_cp_2__8.md
- ssp_template_ia_5__1.md
- ssp_template_sa_22__1.md
- ssp_template_ps_5.md
- ssp_template_au_1.md
- ssp_template_ps_3.md
- ssp_template_sc_7__3.md
- ssp_template_sa_2.md
- ssp_template_pe_4.md
- ssp_template_ia_4.md
- ssp_template_si_8__1.md
- ssp_template_pe_16.md
- ssp_template_pe_13__2.md
- ssp_template_au_3.md
- ssp_template_mp_6__2.md
- ssp_template_cm_2__7.md
- ssp_template_sa_4.md
- ssp_template_si_3__2.md
- ssp_template_ir_3.md
- ssp_template_ps_2.md
- ssp_template_sa_3.md
- ssp_template_cp_6__1.md
- ssp_template_sa_4__10.md
- ssp_template_ir_9__2.md
- ssp_template_sc_7__18.md
- ssp_template_ir_7__1.md
- ssp_template_si_5.md
- ssp_template_mp_4.md
- ssp_template_cp_9.md
- ssp_template_ma_4__2.md
- ssp_template_sc_5.md
- ssp_template_au_3__1.md
- ssp_template_at_3.md
- ssp_template_sc_10.md
- ssp_template_ia_8__3.md
- ssp_template_cp_2__2.md
- ssp_template_si_2.md
- ssp_template_ac_2__3.md
- ssp_template_ma_3__1.md
- ssp_template_ia_5.md
- ssp_template_ra_5.md
- ssp_template_ir_4__1.md
- ssp_template_si_2__2.md
- ssp_template_cm_2.md
- ssp_template_sa_10.md
- ssp_template_sc_4.md
- ssp_template_mp_1.md
- ssp_template_sc_28__1.md
- ssp_template_ir_9__1.md
- ssp_template_ia_2__3.md
- ssp_template_ra_1.md
- ssp_template_au_12.md
- ssp_template_ia_7.md
- ssp_template_ac_4.md
- ssp_template_cp_8__1.md
- ssp_template_ia_8__4.md
- ssp_template_ac_20__1.md
- ssp_template_ac_21.md
- ssp_template_ac_19.md
- ssp_template_ac_6__2.md
- ssp_template_ac_22.md
- ssp_template_ac_20__2.md
- ssp_template_ac_19__5.md
- ssp_template_ac_8.md
- ssp_template_ac_1.md
- ssp_template_ac_18__1.md
- ssp_template_ac_20.md
- ssp_template_ac_18.md
