id: app
title: GovReady-Q
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: NIST SP 800-53 Rev 5 Compliance of GovReady-Q
    long: Generates compliance documentation of GovReady-Q per NIST SP 800-53 Rev
      5 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |-
    DESCR
    This application will make sure you are properly using GovReady-Q to protect an information system per NIST SP 800-53 Rev 5 controls.
protocol:
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/govready-q
output:
- ssp_nistsp80053r5_control_ac_3_impl.md
- ssp_nistsp80053r5_control_ac_6_9_impl.md
- ssp_nistsp80053r5_control_ac_7_impl.md
- ssp_nistsp80053r5_control_ac_8_impl.md
- ssp_nistsp80053r5_control_ac_16_1_impl.md
- ssp_nistsp80053r5_control_au_3_impl.md
- ssp_nistsp80053r5_control_au_5_impl.md
- ssp_nistsp80053r5_control_au_12_impl.md
- ssp_nistsp80053r5_control_ia_2_impl.md
- ssp_nistsp80053r5_control_ia_2_1_impl.md
- ssp_nistsp80053r5_control_ia_2_8_impl.md
- ssp_nistsp80053r5_control_ia_5_1_impl.md
- ssp_nistsp80053r5_control_ia_6_impl.md
- ssp_nistsp80053r5_control_ia_8_impl.md
- ssp_nistsp80053r5_control_ia_11_impl.md
- ssp_nistsp80053r5_control_sc_5_impl.md
- ssp_nistsp80053r5_control_sc_12_impl.md
- ssp_nistsp80053r5_control_sc_13_impl.md
- ssp_nistsp80053r5_control_sc_21_impl.md
