id: app
title: Dockerized GovReady-Q ATO
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: Generate Authority to Operate artifacts for Dockerized GovReady-Q per NIST
      SP 800-53 Rev 5 controls.
    long: Generates compliance artifacts for a Docker deployment of GovReady-Q per
      NIST SP 800-53 Rev 5 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |-
    This app will help you generate Authority to Operate artifacts for the Dockerized deployment of
    GovReady-Q per NIST SP 800-53 Rev 5 controls.
questions:
- id: network_infrastructure
  title: Network Infrastructure
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/network-infrastructure
  group: System Configuration
- id: monitoring_infrastructure
  title: Monitoring Infrastructure
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/monitoring-infrastructure
  group: System Configuration
- id: host_system
  title: Host System
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/unix-host-system
  group: System Configuration
- id: host_web_server
  title: Host Web Server
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/host-web-server
  group: System Configuration
- id: govready_q_component
  title: GovReady-Q
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/govready-q
  group: System Configuration
- id: log_storage
  title: Log Storage
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/log-storage
  group: System Configuration
- id: database
  title: Database
  type: module
  protocol:
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
  - govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/govready.com/govready-q-database
  group: System Configuration
- id: poams
  title: POAMs
  group: Plans of Action and Milestones
  type: module-set
  protocol:
  - govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp/poam
  icon: poam.png
- id: ssp_preview
  title: SSP Preview
  group: System Security Plan
  type: module
  module-id: ssp
- id: control_matrix
  title: Control Matrix
  group: System Security Plan
  type: module
  module-id: matrix
- id: poam_preview
  title: POAMs
  group: System Security Plan
  type: module
  module-id: poams
