id: app
title: Docker Enterprise Edition
type: project
protocol: opencontrol
opencontrol_fetch_date: '2017-05-08T07:45:50.351153+00:00'
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.2
  source_url: https://github.com/GovReady/some-repo-here
  description:
    short: |
      Host your containers in Docker.
    long: >
      This app will help you configure and operate your systems using Docker Enterprise
      Edition, using Docker's official OpenControl data published at [https://github.com/docker/compliance](https://github.com/docker/compliance).
  recommended_for:
  - key_short: Org
    value: Large
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
questions: []
output:
- ssp_template_si_16.md
- ssp_template_cm_5__2.md
- ssp_template_ac_4__8.md
- ssp_template_ac_11.md
- ssp_template_cm_5__3.md
- ssp_template_au_9__2.md
- ssp_template_cm_2.md
- ssp_template_au_5.md
- ssp_template_sc_7__20.md
- ssp_template_au_11.md
- ssp_template_ia_8.md
- ssp_template_ac_2__1.md
- ssp_template_ac_2__12.md
- ssp_template_cm_6__1.md
- ssp_template_ac_2__7.md
- ssp_template_ia_2__8.md
- ssp_template_sc_23__1.md
- ssp_template_sa_10__1.md
- ssp_template_au_9__3.md
- ssp_template_ia_6.md
- ssp_template_ia_5.md
- ssp_template_cm_2__1.md
- ssp_template_au_3__2.md
- ssp_template_ia_7.md
- ssp_template_ac_2__11.md
- ssp_template_au_12__1.md
- ssp_template_au_8__1.md
- ssp_template_ac_5.md
- ssp_template_ac_12.md
- ssp_template_sc_2.md
- ssp_template_ac_6__9.md
- ssp_template_cm_7__5.md
- ssp_template_cm_5__1.md
- ssp_template_ra_5__5.md
- ssp_template_cm_3__6.md
- ssp_template_ac_6__8.md
- ssp_template_cm_1.md
- ssp_template_au_6__4.md
- ssp_template_ac_2__9.md
- ssp_template_ca_7.md
- ssp_template_ra_5__6.md
- ssp_template_sc_23.md
- ssp_template_ra_5__3.md
- ssp_template_ac_1.md
- ssp_template_ia_5__1.md
- ssp_template_ra_5__2.md
- ssp_template_ac_2__10.md
- ssp_template_au_7__1.md
- ssp_template_au_7.md
- ssp_template_au_12.md
- ssp_template_sc_13.md
- ssp_template_ac_12__1.md
- ssp_template_ac_4__21.md
- ssp_template_ac_4.md
- ssp_template_ac_2__2.md
- ssp_template_ia_5__6.md
- ssp_template_au_8.md
- ssp_template_cp_10__2.md
- ssp_template_ia_2.md
- ssp_template_cm_2__3.md
- ssp_template_ia_4.md
- ssp_template_ia_5__2.md
- ssp_template_cm_3__1.md
- ssp_template_ac_2__13.md
- ssp_template_au_12__3.md
- ssp_template_ac_11__1.md
- ssp_template_ac_7.md
- ssp_template_ac_2__4.md
- ssp_template_ia_2__9.md
- ssp_template_au_5__2.md
- ssp_template_si_11.md
- ssp_template_cm_3.md
- ssp_template_au_3.md
- ssp_template_ac_17__2.md
- ssp_template_cm_3__2.md
- ssp_template_sc_12__2.md
- ssp_template_ia_8__3.md
- ssp_template_ac_17__1.md
- ssp_template_cm_7__2.md
- ssp_template_ac_3.md
- ssp_template_au_3__1.md
- ssp_template_ia_5__4.md
- ssp_template_ia_3.md
- ssp_template_ia_2__5.md
- ssp_template_ac_17__9.md
- ssp_template_au_5__1.md
- ssp_template_ac_2__5.md
- ssp_template_au_2.md
- ssp_template_si_3__2.md
- ssp_template_cm_11.md
- ssp_template_ia_4__4.md
- ssp_template_ac_2.md
- ssp_template_sc_28.md
- ssp_template_ia_8__2.md
- ssp_template_au_10.md
- ssp_template_cm_11__1.md
- ssp_template_ac_2__3.md
- ssp_template_cm_2__2.md
- ssp_template_ra_5__1.md
- ssp_template_ac_6__10.md
- ssp_template_sc_28__1.md
- ssp_template_ac_10.md
- ssp_template_cm_9.md
- ssp_template_ac_17__3.md
- ssp_template_ia_8__4.md
- ssp_template_au_9.md
