id: app
title: GitHub Repository
type: project
version: 2
icon: app.png
protocol:
- govready.com/apps/compliance/2018/source-code-repository
- govready.com/apps/compliance/2018/github-source-code-repository
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.1
  source_url: https://github.com/GovReady/govready-apps-dev/apps/GitHub-repo
  description:
    short: |
      Primary GitHub source code repository
    long: |
      Primary GitHub source code repository.
introduction:
  format: markdown
  template: |
    Primary GitHub source code repository.
invitation_to_task_interstitial:
  format: markdown
  template: |
    ## Thanks for accepting {{invitation.from_user}}'s invitation

    You've been asked to help with {{task.title}} for {{project}}.

    We'll tell {{invitation.from_user}} you're getting started.
export_button_label: Export System Description and Control Information
questions:
- id: github_repo
  title: Document GitHub source code repository
  type: module
  module-id: github_repo
  tab: Technical Profile
  group: Technical Summary
