id: app
title: System maintenance
instance-name: |
  {% if description.identifier %}
    {{description.identifier}}
  {% else %}
    New Activity
  {% endif %}
type: project
protocol:
- govready.com/apps/compliance/2018/general/system_maintenance
- govready.com/apps/compliance/2018/general/activity
version: 0.1
icon: app.png
catalog:
  category: Tasks
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.1
  source_url: https://github.com/GovReady/govready-apps-dev/tree/master/out/apps/Activity
  description:
    short: System maintenance tracking
    long: System maintenance tracking
introduction:
  format: markdown
  template: This application will track an adhoc activity
questions:
- id: description
  title: Description of the System Maintenance
  type: module
  module-id: description
- id: progress_log
  title: Progress Log
  type: module-set
  module-id: progress_log
- id: completion
  title: Completion and Approval
  type: module
  module-id: completion
output:
- complete_text.md
