id: app
title: "(DEMO) Basic Website SSP"
type: project
version: 0.1.0
icon: app.png
protocol:
  - govready.com/apps/compliance/2018/information-technology-system
  - govready.com/apps/compliance/2018/demo
instance-name: "{{system_profile.system_basics.system_name}}"
catalog:
  category: IT System Templates
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: candidate release
  version: 0.1.0
  source_url: https://github.com/GovReady/govready-apps-dev/demo-basic-website-ssp
  description:
    short: |
      Demo of creating NIST RMF System Security Plan for a basic website
    long: |
      Use this IT system template for a demonstration of how GovReady-Q compliance as code
      automation makes it easier to generate a System Security Plan for a basic website.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |
      Use this IT system template for a demonstration of how GovReady-Q compliance as code
      automation makes it easier to generate a System Security Plan as described in NIST 
      Special Publication 800-53 Rev 4 for a basic website.
questions:
# System Overview
- id: system_profile
  title: System Profile
  type: module
  protocol: govready.com/apps/compliance/2018/basic-system-description
  group: System Overview
- id: system_categorization
  title: System Categorization
  type: module
  protocol: govready.com/apps/compliance/2018/fisma/system-categorization
  group: System Overview
- id: control_selection
  title: Control Selection Report
  type: module
  module-id: control_selection
  group: System Overview
# Technical Overview
- id: source_code_repo
  title: Source Code Repository
  type: module
  protocol: govready.com/apps/compliance/2018/source-code-repository
  group: Technical Overview

# Technology
- id: web_server
  title: Web Server
  type: module
  protocol: web_server
  group: Technology

- id: infrastructure
  title: Infrastructure
  type: module
  protocol: opencontrol
  group: Technology


# Tasks
- id: actvitity
  title: Actvitity
  group: Tasks
  type: module-set
  protocol:
  - govready.com/apps/compliance/2018/general/activity
- id: poams
  title: POAMs
  group: Tasks
  type: module-set
  protocol:
  - govready.com/apps/compliance/2018/POAM
  icon: app.png

# People
# - id: fed_poc_pm
#   title: PM
#   type: module
#   protocol: fed_poc_pm
#   icon: person-3.png
#   group: People

# - id: fed_poc_developer
#   title: Developer
#   type: module
#   protocol: fed_poc_developer
#   icon: person-3.png
#   group: People

- id: fed_poc_issm
  title: ISSM
  type: module
  protocol: fed_poc_issm
  icon: person-3.png
  group: People

- id: fed_poc_isso
  title: ISSO
  type: module
  protocol: fed_poc_isso
  icon: person-3.png
  group: People

# - id: fed_poc_ciso
#   title: CISO
#   type: module
#   protocol: fed_poc_ciso
#   icon: person-3.png
#   group: People

# - id: fed_poc_ao
#   title: AO
#   type: module
#   protocol: fed_poc_ao
#   icon: person-3.png
#   group: People

# Policy
- id: rules_of_behavior
  title: Rules of Behavior
  type: module
  protocol: govready.com/apps/compliance/2017/rules-of-behavior
  group: Policy
# - id: sm_policy_privacy
#   title: Privacy Policy
#   type: module
#   protocol: sm_policy_privacy
#   group: Policy
# - id: si_policy
#   title: System and Information Integrity Policy and Procedures
#   type: module
#   protocol: govready.com/apps/compliance/2018/si-policy
#   group: Policy

# Artifacts
- id: ssp
  title: View SSP
  type: module
  module-id: ssp
  icon: checkmark.png
  placement: action-buttons
output:
  - id: govready_lifecycle_stage_code
    format: text
    template: |
      {% if not system_profile.is_finished() or not system_categorization.is_finished() %}
        us_nist_rmf_1_categorize
      {% elif not control_selection.is_finished() %}
        us_nist_rmf_2_select
      {% else %}
        us_nist_rmf_3_implement
      {% endif %}
